---

- name: Create RHEL7 VM from template
  hosts: ansible-demo
  connection: local
  gather_facts: false
  roles:
    - create_vm

- name: Connect to VM and configure
  hosts: ansible-demo
  roles:
    - common

