---

- name: Create RHEL7 VM from template
  hosts: rhv-m
  connection: local
  gather_facts: false
  roles:
    - create_vm

- name: Connect to VM and configure
  hosts: rhv-m
  roles:
    - common
    - rhv-m
