---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Subscribe to CDN
  redhat_subscription:
    state: present
    activationkey: "{{ rhsm_key }}"
    org_id: "{{ rhsm_org }}"

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable rhel-7-server-rpms
  rhsm_repository:
    name: rhel-7-server-rpms
    state: enabled

- name: Expand root partition
  shell: growpart /dev/vda 1
  register: grow
  ignore_errors: true

- name: Grow root filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vda1
    resizefs: yes

